name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-02-25"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow"
database_id = "a79b6b69-58be-4443-860c-2b1471a397c5"
